-- ============================================================
-- MIGRACIÓN CEMP — Itagüí BD Colaboradores
-- Ejecutar UNA sola vez en Supabase → SQL Editor → Run
-- Es seguro volver a ejecutarla: no borra información.
-- ============================================================

-- 1. Campos de la ficha completa (mismas 6 secciones del CEMP)
ALTER TABLE colaboradores
  -- Personal
  ADD COLUMN IF NOT EXISTS tipo_documento      TEXT,
  ADD COLUMN IF NOT EXISTS pais_documento      TEXT,
  ADD COLUMN IF NOT EXISTS primer_nombre       TEXT,
  ADD COLUMN IF NOT EXISTS segundo_nombre      TEXT,
  ADD COLUMN IF NOT EXISTS primer_apellido     TEXT,
  ADD COLUMN IF NOT EXISTS segundo_apellido    TEXT,
  ADD COLUMN IF NOT EXISTS genero              TEXT,
  ADD COLUMN IF NOT EXISTS fecha_nacimiento    TEXT,
  ADD COLUMN IF NOT EXISTS pais_nacimiento     TEXT,
  ADD COLUMN IF NOT EXISTS depto_nacimiento    TEXT,
  ADD COLUMN IF NOT EXISTS ciudad_nacimiento   TEXT,
  ADD COLUMN IF NOT EXISTS nombre_preferencia  TEXT,
  -- Ubicación y contacto
  ADD COLUMN IF NOT EXISTS indicativo          TEXT DEFAULT '+57',
  ADD COLUMN IF NOT EXISTS pais_residencia     TEXT,
  ADD COLUMN IF NOT EXISTS ciudad_residencia   TEXT,
  ADD COLUMN IF NOT EXISTS direccion           TEXT,
  -- Espiritual
  ADD COLUMN IF NOT EXISTS iglesia_inicio          TEXT,
  ADD COLUMN IF NOT EXISTS bautismo_es             BOOLEAN,
  ADD COLUMN IF NOT EXISTS fecha_congrega_actual   TEXT,
  ADD COLUMN IF NOT EXISTS iglesia_actual          TEXT,
  ADD COLUMN IF NOT EXISTS lecturas_biblia         INTEGER,
  ADD COLUMN IF NOT EXISTS lecturas_vivencias      INTEGER,
  ADD COLUMN IF NOT EXISTS instituto_participo     BOOLEAN,
  ADD COLUMN IF NOT EXISTS instituto_presencial    BOOLEAN,
  ADD COLUMN IF NOT EXISTS instituto_presencial_veces INTEGER,
  ADD COLUMN IF NOT EXISTS instituto_audio         BOOLEAN,
  ADD COLUMN IF NOT EXISTS instituto_audio_veces   INTEGER,
  ADD COLUMN IF NOT EXISTS es_fimlm                BOOLEAN,
  ADD COLUMN IF NOT EXISTS es_mira                 BOOLEAN,
  ADD COLUMN IF NOT EXISTS fechas_dones            JSONB DEFAULT '{}'::JSONB,
  -- Labores
  ADD COLUMN IF NOT EXISTS fechas_labores          JSONB DEFAULT '{}'::JSONB,
  ADD COLUMN IF NOT EXISTS labores_inactivas       JSONB DEFAULT '[]'::JSONB,
  -- Educación
  ADD COLUMN IF NOT EXISTS estudios                JSONB DEFAULT '[]'::JSONB,
  ADD COLUMN IF NOT EXISTS idiomas                 JSONB DEFAULT '[]'::JSONB,
  ADD COLUMN IF NOT EXISTS ocupacion               TEXT,
  -- Salud
  ADD COLUMN IF NOT EXISTS salud_afiliado          BOOLEAN,
  ADD COLUMN IF NOT EXISTS salud_entidad           TEXT,
  -- Autorización de tratamiento de datos (Ley 1581)
  ADD COLUMN IF NOT EXISTS consentimiento_datos    BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS consentimiento_fecha    TIMESTAMPTZ,
  -- Control CEMP
  ADD COLUMN IF NOT EXISTS cemp_fecha_registro     TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS cemp_registrado_por     TEXT,
  ADD COLUMN IF NOT EXISTS datos_actualizados_en   TIMESTAMPTZ;

-- 2. Bandeja de solicitudes del formulario público
CREATE TABLE IF NOT EXISTS solicitudes (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cedula         TEXT NOT NULL,
  datos          JSONB NOT NULL,
  estado         TEXT NOT NULL DEFAULT 'pendiente',   -- pendiente | aprobada | rechazada
  colaborador_id BIGINT,
  creado_en      TIMESTAMPTZ DEFAULT NOW(),
  revisado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS solicitudes_estado_idx ON solicitudes (estado);

-- 3. Desactivar temporalmente la marca automática mientras se ajustan los datos existentes
DROP TRIGGER IF EXISTS trg_datos_actualizados ON colaboradores;

-- 4. Pasar las labores al catálogo oficial del CEMP
--    Vigilancia → Logística (Vigilancia) · Llaves → Llaves de la iglesia · Cámaras → Video
--    Apoyo Ofrenda → Ofrenda (Grupo 1 - Recolector)
--    Ofrenda Interno / Ofrenda Organización → Ofrenda (Grupo 2)
--    La distinción Interno / Organización se conserva en observaciones.
UPDATE colaboradores
SET observaciones = TRIM(BOTH '; ' FROM CONCAT_WS('; ', NULLIF(observaciones, ''),
      CASE WHEN labores @> '["Ofrenda Interno"]'::jsonb      THEN 'Ofrenda: Interno' END,
      CASE WHEN labores @> '["Ofrenda Organización"]'::jsonb THEN 'Ofrenda: Organización' END))
WHERE (labores @> '["Ofrenda Interno"]'::jsonb OR labores @> '["Ofrenda Organización"]'::jsonb)
  AND COALESCE(observaciones, '') NOT LIKE '%Ofrenda: %';

UPDATE colaboradores c
SET labores = sub.nuevas
FROM (
  SELECT id, COALESCE(jsonb_agg(DISTINCT m.labor), '[]'::jsonb) AS nuevas
  FROM colaboradores,
  LATERAL (
    SELECT CASE e
      WHEN 'Vigilancia'           THEN 'Logística (Vigilancia)'
      WHEN 'Llaves'               THEN 'Llaves de la iglesia'
      WHEN 'Cámaras'              THEN 'Video'
      WHEN 'Apoyo Ofrenda'        THEN 'Ofrenda (Grupo 1 - Recolector)'
      WHEN 'Ofrenda Interno'      THEN 'Ofrenda (Grupo 2)'
      WHEN 'Ofrenda Organización' THEN 'Ofrenda (Grupo 2)'
      ELSE e END AS labor
    FROM jsonb_array_elements_text(COALESCE(labores, '[]'::jsonb)) AS e
  ) m
  GROUP BY id
) sub
WHERE c.id = sub.id;

-- 5. Separar el nombre completo en nombres y apellidos cuando aún no existan
--    (aproximado: 2 palabras = nombre + apellido; 3 = nombre + 2 apellidos; 4+ = 2 nombres + 2 apellidos)
UPDATE colaboradores SET
  primer_nombre    = split_part(n, ' ', 1),
  segundo_nombre   = CASE WHEN cnt >= 4 THEN split_part(n, ' ', 2) END,
  primer_apellido  = CASE WHEN cnt = 2 THEN split_part(n, ' ', 2)
                          WHEN cnt = 3 THEN split_part(n, ' ', 2)
                          ELSE split_part(n, ' ', 3) END,
  segundo_apellido = CASE WHEN cnt = 3 THEN split_part(n, ' ', 3)
                          WHEN cnt >= 4 THEN split_part(n, ' ', 4) END
FROM (
  SELECT id AS cid, regexp_replace(trim(nombre), '\s+', ' ', 'g') AS n,
         array_length(regexp_split_to_array(trim(nombre), '\s+'), 1) AS cnt
  FROM colaboradores
) x
WHERE colaboradores.id = x.cid AND colaboradores.primer_nombre IS NULL AND x.cnt >= 2;

-- 6. Quienes ya tienen roles en MIRA / FIMLM quedan marcados como voluntarios
UPDATE colaboradores SET es_mira  = TRUE WHERE es_mira  IS NULL AND jsonb_array_length(COALESCE(mira,  '[]'::jsonb)) > 0;
UPDATE colaboradores SET es_fimlm = TRUE WHERE es_fimlm IS NULL AND jsonb_array_length(COALESCE(fimlm, '[]'::jsonb)) > 0;

-- 7. Iglesia actual por defecto
UPDATE colaboradores SET iglesia_actual = 'IG68 · Itagüí · Calle 51 # 40 - 159 Barrio La Cruz'
WHERE iglesia_actual IS NULL;

-- 8. Marca automática de "datos actualizados"
--    Cuando cambia información que también está en el CEMP, se guarda la fecha.
--    Si esa fecha es posterior al último registro en CEMP, la ficha queda "Desactualizada".
CREATE OR REPLACE FUNCTION tocar_datos_actualizados() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
  ignorar TEXT[] := ARRAY[
    'cemp_fecha_registro','cemp_registrado_por','datos_actualizados_en',
    'activo','mira','fimlm','dia_profecia','horario','observaciones',
    'creado_en','consentimiento_datos','consentimiento_fecha'
  ];
BEGIN
  -- Si en esta misma operación se marcó el registro en CEMP, no se considera desactualizado
  IF NEW.cemp_fecha_registro IS DISTINCT FROM OLD.cemp_fecha_registro THEN
    RETURN NEW;
  END IF;
  IF (to_jsonb(NEW) - ignorar) IS DISTINCT FROM (to_jsonb(OLD) - ignorar) THEN
    NEW.datos_actualizados_en := NOW();
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_datos_actualizados ON colaboradores;
CREATE TRIGGER trg_datos_actualizados
  BEFORE UPDATE ON colaboradores
  FOR EACH ROW EXECUTE FUNCTION tocar_datos_actualizados();

-- Verificación
SELECT COUNT(*) AS colaboradores,
       COUNT(*) FILTER (WHERE primer_nombre IS NOT NULL) AS con_nombres_separados
FROM colaboradores;
