-- ============================================================
-- ESQUEMA DE BASE DE DATOS — San Diego 5 PM
-- Ejecutar en Supabase → SQL Editor
-- ============================================================

-- Tabla principal de colaboradores
CREATE TABLE IF NOT EXISTS colaboradores (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre    TEXT NOT NULL,
  cedula    TEXT,
  celular   TEXT,
  email     TEXT,
  horario   TEXT DEFAULT '7:00 AM',
  foto      TEXT,
  dones     JSONB DEFAULT '[]'::JSONB,
  labores   JSONB DEFAULT '[]'::JSONB,
  mira      JSONB DEFAULT '[]'::JSONB,
  fimlm     JSONB DEFAULT '[]'::JSONB,
  fecha_inicio    TEXT,
  fecha_espiritu  TEXT,
  fecha_profecia  TEXT,
  observaciones   TEXT,
  activo    INTEGER DEFAULT 1,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de estudiantes del Instituto Bíblico
CREATE TABLE IF NOT EXISTS estudiantes (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre          TEXT NOT NULL,
  cedula          TEXT NOT NULL UNIQUE,
  celular         TEXT,
  foto            TEXT,
  activo          INTEGER DEFAULT 1,
  orden           INTEGER,
  creado_en       TIMESTAMPTZ DEFAULT NOW(),
  actualizado_en  TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de sesiones del Instituto
CREATE TABLE IF NOT EXISTS sesiones (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha       TEXT NOT NULL,
  descripcion TEXT,
  creado_en   TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de asistencias
CREATE TABLE IF NOT EXISTS asistencias (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sesion_id      BIGINT NOT NULL REFERENCES sesiones(id) ON DELETE CASCADE,
  estudiante_id  BIGINT NOT NULL REFERENCES estudiantes(id) ON DELETE CASCADE,
  asistio        INTEGER DEFAULT 0,
  nota           TEXT,
  registrado_en  TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- STORAGE: crear bucket público para fotos
-- Esto se hace en Supabase → Storage → New Bucket
-- Nombre: "fotos", tipo: Public
-- ============================================================
